#the environment.yml file tailored for your AI-powered drug discovery project. This file facilitates setting up a Conda environment with all 
#the necessary dependencies for data processing, model training, molecule generation, optimization, and the Streamlit-based web interface
name: natural-product-drug-discovery
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - rdkit=2022.9.5
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pip
  - pip:
      - torch-geometric==2.3.0
      - streamlit==1.25.0
      - Pillow==10.0.0
